Repository Vanilla-OS/apx, pull requests merged in 2023-03, with the labels that each got.

#148 Add gitattributes for default eof
  .gitattributes
Labels: enhancement

#155 README: Update other distro instructions
  README.md
Labels: enhancement

#163 Remove pt_br cmd help
  lang/pt_br/cmd_help
Labels: translation

#165 Add install-manpage target in makefile and update readme
  Makefile
  README.md
  debian/apx.install
  man/es/man1/apx.1
  man/man1/apx.1
  man/sv/man1/apx.1
Labels: documentation, enhancement

#177 Translations update from Hosted Weblate
  locales/sv.yml
  locales/ta.yml
Labels: translation

#169 README: Add community packages
  README.md
Labels: enhancement
